resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/00487726c4bc21b4744e59d913334ebfeac7d68e/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
  ouroboros-consensus:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 156391afaafca6b00d027fb9c03e1bd7a1f03003
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 80deee31f8d9422b8e090e55b17e1a714153180b
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 5e05950c54b64e9fd10804065aaca9f552fd638d
    subdirs:
      - byron/semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: ae3ba75be91b3dde0c46e71cc029de55e0a63735
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 00487726c4bc21b4744e59d913334ebfeac7d68e
    subdirs:
      - .
      - test

  - git: https://github.com/advancedtelematic/quickcheck-state-machine
    commit: 41718e9b17e3151178ce27600f84ca1d9d852c65
    subdirs:
      - .

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - splitmix-0.0.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3
<<<<<<< HEAD
  - network-3.1.0.1
=======
  - these-0.8
  - assoc-1
  - QuickCheck-2.13.2@sha256:ad4e5adbd1c9dc0221a44307b992cb040c515f31095182e47aa7e974bc461df1,6952
  - markov-chain-usage-model-0.0.0@sha256:1afa95faeb9213c4d960a669190078b41b89169462b8edd910472980671ba8c0,2112
>>>>>>> Use newer qsm version

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
